# Generated by Django 5.2.4 on 2025-07-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
